import type { Config } from "tailwindcss";

export default {
  darkMode: ["class"],
  content: ["./pages/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}", "./app/**/*.{ts,tsx}", "./src/**/*.{ts,tsx}"],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: { "2xl": "1400px" },
    },
    extend: {
      fontFamily: {
        roboto: ["Roboto", "Arial", "sans-serif"],
        chirp: ["Chirp", "system-ui", "-apple-system", "BlinkMacSystemFont", "sans-serif"],
        retro: ["DotGothic16", "monospace"],
      },
      colors: {
        yt: {
          "bg-primary": "rgb(var(--yt-bg-primary) / <alpha-value>)",
          "bg-secondary": "rgb(var(--yt-bg-secondary) / <alpha-value>)",
          "bg-tertiary": "rgb(var(--yt-bg-tertiary) / <alpha-value>)",
          "text-primary": "rgb(var(--yt-text-primary) / <alpha-value>)",
          "text-secondary": "rgb(var(--yt-text-secondary) / <alpha-value>)",
          red: "rgb(var(--yt-red) / <alpha-value>)",
          blue: "rgb(var(--yt-blue) / <alpha-value>)",
          border: "rgb(var(--yt-border) / <alpha-value>)",
          hover: "rgb(var(--yt-hover) / <alpha-value>)",
        },
        tw: {
          "bg-primary": "rgb(var(--tw-bg-primary) / <alpha-value>)",
          "bg-secondary": "rgb(var(--tw-bg-secondary) / <alpha-value>)",
          "bg-hover": "rgb(var(--tw-bg-hover) / <alpha-value>)",
          "text-primary": "rgb(var(--tw-text-primary) / <alpha-value>)",
          "text-secondary": "rgb(var(--tw-text-secondary) / <alpha-value>)",
          blue: "rgb(var(--tw-blue) / <alpha-value>)",
          "blue-hover": "rgb(var(--tw-blue-hover) / <alpha-value>)",
          border: "rgb(var(--tw-border) / <alpha-value>)",
        },
        wa: {
          "bg-primary": "rgb(var(--wa-bg-primary) / <alpha-value>)",
          "bg-secondary": "rgb(var(--wa-bg-secondary) / <alpha-value>)",
          "bg-header": "rgb(var(--wa-bg-header) / <alpha-value>)",
          "bg-input": "rgb(var(--wa-bg-input) / <alpha-value>)",
          "bg-hover": "rgb(var(--wa-bg-hover) / <alpha-value>)",
          "bg-active": "rgb(var(--wa-bg-active) / <alpha-value>)",
          "chat-bg": "rgb(var(--wa-chat-bg) / <alpha-value>)",
          "bubble-incoming": "rgb(var(--wa-bubble-incoming) / <alpha-value>)",
          "bubble-outgoing": "rgb(var(--wa-bubble-outgoing) / <alpha-value>)",
          "text-primary": "rgb(var(--wa-text-primary) / <alpha-value>)",
          "text-secondary": "rgb(var(--wa-text-secondary) / <alpha-value>)",
          green: "rgb(var(--wa-green) / <alpha-value>)",
          "green-dark": "rgb(var(--wa-green-dark) / <alpha-value>)",
          border: "rgb(var(--wa-border) / <alpha-value>)",
        },
        retro: {
          red: "rgb(var(--retro-red) / <alpha-value>)",
          green: "rgb(var(--retro-green) / <alpha-value>)",
          blue: "rgb(var(--retro-blue) / <alpha-value>)",
          muted: "rgb(var(--retro-muted) / <alpha-value>)",
          button: "rgb(var(--retro-button) / <alpha-value>)",
          "button-text": "rgb(var(--retro-button-text) / <alpha-value>)",
          "button-hover": "rgb(var(--retro-button-hover) / <alpha-value>)",
        },
        twitter: {
          blue: "rgb(var(--tw-blue) / <alpha-value>)",
        },
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: { DEFAULT: "hsl(var(--primary))", foreground: "hsl(var(--primary-foreground))" },
        secondary: { DEFAULT: "hsl(var(--secondary))", foreground: "hsl(var(--secondary-foreground))" },
        destructive: { DEFAULT: "hsl(var(--destructive))", foreground: "hsl(var(--destructive-foreground))" },
        muted: { DEFAULT: "hsl(var(--muted))", foreground: "hsl(var(--muted-foreground))" },
        accent: { DEFAULT: "hsl(var(--accent))", foreground: "hsl(var(--accent-foreground))" },
        popover: { DEFAULT: "hsl(var(--popover))", foreground: "hsl(var(--popover-foreground))" },
        card: { DEFAULT: "hsl(var(--card))", foreground: "hsl(var(--card-foreground))" },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": { from: { height: "0" }, to: { height: "var(--radix-accordion-content-height)" } },
        "accordion-up": { from: { height: "var(--radix-accordion-content-height)" }, to: { height: "0" } },
        "fade-in": { "0%": { opacity: "0", transform: "translateY(10px)" }, "100%": { opacity: "1", transform: "translateY(0)" } },
        shake: { "0%, 100%": { transform: "translateX(0)" }, "25%": { transform: "translateX(-5px)" }, "75%": { transform: "translateX(5px)" } },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "fade-in": "fade-in 0.3s ease-out",
        shake: "shake 0.3s ease-in-out",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
} satisfies Config;
